### ISSUE TITLE
Magisk Delta (25206) to the latest f470988f-delta(25210) build is causing permissions denied mayhem

### ISSUE THREAD

**Issue by lordmemed** [HuskyDG/magisk-files#91]
### The Problem
Delta version 25206 and the latest is causing permissions denied errors for even system apps, especially on `/data/user/0/*`
The most stable for me is 252-delta-3, but this version can't enable zygisk :/ while in the latest 25210 zygisk can be enabled. 

### Logs
Sorry that i can't capture/upload the logcat here, because it is too big to be a log file more than 100MB and increasing each passing second if i capture it, and generally it just repeating the same errors.

`03-20 18:16:04.373 15865 43226 W FileUtils: Failed to chmod(/data/user/0/com.google.android.gms/app_dg_cache): android.system.ErrnoException: chmod failed: EACCES (Permission denied)`

>Example of partial logcat
...
03-20 18:16:04.378 114584 49048 D AndroidRuntime: Shutting down VM
03-20 18:16:04.378 114584 49048 E AndroidRuntime: FATAL EXCEPTION: main
03-20 18:16:04.378 114584 49048 E AndroidRuntime: Process: com.google.process.gservices, PID: 114584
03-20 18:16:04.378 114584 49048 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gsf.gservices.GservicesProvider: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.google.android.gsf/databases/gservices.db': Directory /data/user/0/com.google.android.gsf/databases doesn't exist
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7252)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6788)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6705)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7665)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.google.android.gsf/databases/gservices.db': Directory /data/user/0/com.google.android.gsf/databases doesn't exist
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at com.google.android.gsf.gservices.GservicesProvider.computeLocalDigestAndUpdateValues(GservicesProvider.java:450)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at com.google.android.gsf.gservices.GservicesProvider.onCreate(GservicesProvider.java:185)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7247)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	... 10 more
03-20 18:16:04.378 114584 49048 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
03-20 18:16:04.378 114584 49048 E AndroidRuntime: 	... 25 more
03-20 18:16:04.379 15865 43226 W ContextImpl: Failed to ensure /data/user/0/com.google.android.gms/databases: mkdir failed: EACCES (Permission denied)
03-20 18:16:04.379 15865 43226 E SQLiteLog: (14) cannot open file at line 38844 of [d2e6722037]
03-20 18:16:04.379 15865 43226 E SQLiteLog: (14) os_unix.c:38844: (13) lstat(/data/user/0/com.google.android.gms/databases/dgp.db) - 
03-20 18:16:04.373 15865 43226 W FileUtils: Failed to chmod(/data/user/0/com.google.android.gms/app_dg_cache): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
...

<details>
<summary>Instead of a file, i just can share a few screenshots</summary>

![Screenshot_2023-03-21_01-38-53](https://user-images.githubusercontent.com/31779906/226437060-dd8f9fae-f056-4d46-abf4-fec4c5ee7ebd.png)

![Screenshot_2023-03-21_01-38-22](https://user-images.githubusercontent.com/31779906/226437107-d53c34c6-5590-420d-8731-e84c8a38d69c.png)

![Screenshot_2023-03-21_01-15-31](https://user-images.githubusercontent.com/31779906/226437178-d652ed22-0860-4645-8919-5eaf0027cc2a.png)

</details> 

### Device
ROM : LineageOS 18.1 Waydroid Android 11
Architecture : x86_64

### Question
What could be the cause?
Why would Magisk Delta causing a havoc/mayhem of apps/file/folder permissions?

**Comment by lordmemed** [comment]
> > Why would Magisk Delta causing a havoc/mayhem of apps/file/folder permissions?
> 
> I don't think Magisk Delta could cause this problem. Maybe your installer script problem

Thank you and sorry for this.

Yes, after more investigation of what might be the cause, i get a few of them :
1. Magisk bootanim.rc script failed to load because it can't access `/sbin` folder, Read-Only filesystem;
2. After moving the mount folder to somewhere else (in my case to `/dev/magisk`), it will run, but with problem;
3. The problem is, magiskpolicy service failed to start, Read-Only filesystem, thus causing this madness.

So, to alleviate this problem, what work for me is this :
1. Editing bootanim.rc with this;
<details>
<summary>my post-fs-data in bootanim.rc script</summary>
`on post-fs-data
    start logd

    mkdir /dev/wsa-magisk
    mount tmpfs tmpfs /dev/wsa-magisk mode=0755
    copy /system/etc/init/magisk/magisk64 /dev/wsa-magisk/magisk64
    chmod 0755 /dev/wsa-magisk/magisk64
    copy /system/etc/init/magisk/magisk32 /dev/wsa-magisk/magisk32
    chmod 0755 /dev/wsa-magisk/magisk32
    symlink ./magisk32 /dev/wsa-magisk/magisk
    symlink ./magisk64 /dev/wsa-magisk/su
    symlink ./magisk64 /dev/wsa-magisk/resetprop
    copy /system/etc/init/magisk/magiskinit /dev/wsa-magisk/magiskinit
    chmod 0755 /dev/wsa-magisk/magiskinit
    
    # 24107
    copy /system/etc/init/magisk/magiskpolicy /dev/wsa-magisk/magiskpolicy	
    chmod 0755 /dev/wsa-magisk/magiskpolicy
    copy /system/etc/init/magisk/magisk.apk /dev/wsa-magisk/stub.apk

    exec u:r:su:s0 root root -- /system/etc/init/magisk/magiskpolicy --live --magisk
    exec u:r:magisk:s0 root root -- /system/etc/init/magisk/magiskpolicy --live --magisk
    exec u:r:update_engine:s0 root root -- /system/etc/init/magisk/magiskpolicy --live --magisk
    exec u:r:su:s0 root root -- /system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk
    mkdir /dev/wsa-magisk/.magisk 700
    mkdir /dev/wsa-magisk/.magisk/mirror 700
    mkdir /dev/wsa-magisk/.magisk/block 700
    copy /system/etc/init/magisk/config /dev/wsa-magisk/.magisk/config
    rm /dev/.magisk_unblock
    start IhhslLhHYfse

    exec u:r:su:s0 root root -- /dev/wsa-magisk/magisk --auto-selinux --post-fs-data
    wait /dev/.magisk_unblock 40
    rm /dev/.magisk_unblock

service IhhslLhHYfse /system/bin/sh /magisk/loadpolicy.sh
    user root
    seclabel u:r:magisk:s0
    oneshot

on nonencrypted
    exec u:r:su:s0 root root -- /dev/wsa-magisk/magisk --auto-selinux --service

on property:sys.boot_completed=1
    mkdir /data/adb/magisk 755
    exec u:r:su:s0 root root -- /dev/wsa-magisk/magisk --auto-selinux --boot-complete
   
on property:init.svc.zygote=restarting
    exec u:r:su:s0 root root -- /dev/wsa-magisk/magisk --auto-selinux --zygote-restart
   
on property:init.svc.zygote=stopped
    exec u:r:su:s0 root root -- /dev/wsa-magisk/magisk --auto-selinux --zygote-restart
`
</details>
<details>
<summary>loadpolicy.sh script</summary>
`#!/system/bin/sh
restorecon -R /data/adb/magisk
for module in $(ls /data/adb/modules); do
    if ! [ -f /data/adb/modules/$module/disable ] && [ -f /data/adb/modules/$module/sepolicy.rule ]; then
        /magisk/magiskpolicy --live --apply /data/adb/modules/$module/sepolicy.rule
    fi
done
`
</details>

`Some Screenshot if you want to see`
<details>
<summary>Nice</summary>
![Screenshot_2023-03-21_11-30-53](https://user-images.githubusercontent.com/31779906/226518237-fdc564e8-bca8-4ed2-9adb-3669abd80ce1.png)
![Screenshot_2023-03-21_11-31-06](https://user-images.githubusercontent.com/31779906/226518244-7b95255d-9655-436a-9ed0-07c0a8e367db.png)

</details>

Maybe  this can be reference if someone encounter a _unique_ problem like mine with their Magisk setup.

Oh, more info about what Android Device i use :
Freshly installed Android 11 on Waydroid platform in ArchLinux.

Thanks for the attention.
👍🏼 

Regards,
LordMEMED
